Test AMD64 Dockerfile

diff --git a/docker/Dockerfile.test b/docker/Dockerfile.test
--- a/docker/Dockerfile.test
+++ b/docker/Dockerfile.test
@@ -60,8 +60,8 @@ RUN ls -l
 #RUN cpanm LWP::UserAgent
 RUN /usr/bin/curl -L -o carton.tgz https://github.com/perl-carton/carton/archive/refs/tags/v1.0.35.tar.gz 
 RUN ls -l
-RUN cpanm ./carton.tgz
-RUN cpanm --notest Carton || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
+RUN cpanm ./carton.tgz || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
+#RUN cpanm --notest Carton || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
 #RUN cpanm --notest https://github.com/perl-carton/carton/archive/refs/tags/v1.0.35.tar.gz || (echo "Carton install failed. Dumping build.log:" && cat /root/.cpanm/work/*/build.log && exit 1)
 
 
