Added two missing test files causing build to fail

diff --git a/docker/Dockerfile.alpine b/docker/Dockerfile.alpine
--- a/docker/Dockerfile.alpine
+++ b/docker/Dockerfile.alpine
@@ -103,13 +103,8 @@ RUN carton install --deployment
 #
 WORKDIR ..
 #RUN carton exec -- cpanm --local-lib-contained=${PERL_CARTON_PATH} .
-RUN carton exec -- cpanm . || true
-
-
-#  Dump out build logs
-#
-RUN cat /root/.cpanm/work/*/build.log
-
+#RUN carton exec -- cpanm .
+RUN set -e; carton exec -- cpanm . || { rc=$?; echo "Build failed:"; find /root/.cpanm/work -name build.log -exec cat {} \;; exit $rc; }
 
 # Clean carton cache and create empty webdyne cache dir
 RUN rm -rf ${PERL_CARTON_PATH}/cache
@@ -171,9 +166,9 @@ LABEL org.opencontainers.image.source="https://github.com/aspeer/WebDyne.git"
 LABEL org.opencontainers.image.documentation="https://github.com/aspeer/WebDyne#readme"
 LABEL org.opencontainers.image.authors="Andrew Speer <andrew.speer@isolutions.com.au>"
 LABEL org.opencontainers.image.licenses="Artistic-1.0-Perl OR GPL-1.0-or-later"
-LABEL org.opencontainers.image.created="2026-01-03T02:10:49Z"
+LABEL org.opencontainers.image.created="2026-01-03T03:00:34Z"
 LABEL org.opencontainers.image.version="2.042"
-LABEL org.opencontainers.image.revision="2fc75de"
+LABEL org.opencontainers.image.revision="d99451a"
 LABEL org.opencontainers.image.base=${BASE}
 
 
diff --git a/docker/Dockerfile.tt b/docker/Dockerfile.tt
--- a/docker/Dockerfile.tt
+++ b/docker/Dockerfile.tt
@@ -127,13 +127,8 @@ RUN carton install --deployment
 #
 WORKDIR ..
 #RUN carton exec -- cpanm --local-lib-contained=${PERL_CARTON_PATH} .
-RUN carton exec -- cpanm . || true
-
-
-#  Dump out build logs
-#
-RUN cat /root/.cpanm/work/*/build.log
-
+#RUN carton exec -- cpanm .
+RUN set -e; carton exec -- cpanm . || { rc=$?; echo "Build failed:"; find /root/.cpanm/work -name build.log -exec cat {} \;; exit $rc; }
 
 # Clean carton cache and create empty webdyne cache dir
 RUN rm -rf ${PERL_CARTON_PATH}/cache
